name: react-ci
on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      backend:
        command: |
          cd backend
          pip install -r requirements.txt
          python manage.py migrate
          python manage.py runserver localhost:8000
        ports:
          - 8000:8000

    env:
      VITE_APP_BACKEND: ${{ secrets.VITE_APP_BACKEND }}
      VITE_APP_FRONTEND: ${{ secrets.VITE_APP_FRONTEND }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js for frontend
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies
        run: |
          cd frontend/
          npm install

      - name: Run frontend build and tests
        run: |
          cd frontend/
          npm run test

      - name: Stop Django backend
        run: kill $(jobs -p) || true